name: Python Unittest and Coverage

on: [ push, pull_request ]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage coverage-badge pytest-cov

      - name: Remove existing coverage badge
        run: rm -f ./docs/coverage.svg

      - name: Run Unittests and Generate Coverage Report

        run: |
          pytest --cov=flask_schema tests/
          coverage xml
          coverage-badge -o ./docs/source/_static/coverage.svg
      # Commit and Push Coverage Badge
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update coverage badge
          file_pattern: docs/source/_static/coverage.svg
          commit_options: '--no-verify'
          branch: master
