name: Publish to PyPI

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure tags are fetched for semantic-release
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install build and semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install build python-semantic-release
      - name: Semantic release version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release version --skip-build
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
