# NOTE: This workflow is disabled because python-semantic-release now publishes to PyPI.
# If you prefer to publish on GitHub Release instead of on push, delete .github/workflows/release.yml
# and re-enable this job by removing the "if: false" and switching `on:` to "release: types: [published]".
name: Publish to PyPI (disabled - using semantic-release)
on:
  push:
    branches: [ master ]

jobs:
  publish:
    if: false  # semantic-release handles publishing now
    runs-on: ubuntu-latest
    steps:
      - run: echo "Publishing handled by semantic-release. See .github/workflows/release.yml"
