name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build + semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install build python-semantic-release

      - name: Semantic release (bump, tag, changelog, GitHub Release, PyPI)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: semantic-release publish
