name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need full history & tags

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build + semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install build python-semantic-release

      - name: Semantic release (bump version, tag, changelog, GitHub Release, upload to PyPI)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # provided by GitHub
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}   # add this in repo Settings → Secrets and variables → Actions
        run: semantic-release publish
