name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest coverage[toml] coverage-badge
      - name: Lint with ruff
        run: ruff check --output-format=github --no-cache .
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=95
          coverage xml
          coverage-badge -o coverage.svg
          coverage-badge -o docs/source/_static/coverage.svg
